title: Jekyll Site
author: CE
email: charles-eaton@live.com
description: > # this means to ignore newlines until "baseurl:"
  A practice site using GitHub Pages and Jekyll

theme: minima

# social links
github_username:  ceato

show_excerpts: true # set to false to remove excerpts on the homepage

